import fs from 'node:fs'

const file = new URL('../src/App.tsx', import.meta.url)
let s = fs.readFileSync(file, 'utf8')

const replacements = [
  ["subtitulo: 'Colocando ordem nos canais internos e mostrando a força da marca no mercado.'", "subtitulo: 'Comunicação corporativa, canais digitais e projetos em uma estrutura de grande porte.'"],
  ["contexto: 'O Grupo SADA reúne mais de 30 marcas e é o maior grupo de logística e transporte de veículos da América Latina, com operações em 4 estados e +8.000 colaboradores. A área de comunicação estava em processo de estruturação, sem processos definidos, sem padronização editorial e com presença digital incipiente.'", "contexto: 'No Grupo SADA, atuei na Gerência de Comunicação e Marketing em um contexto corporativo amplo, com diferentes empresas, áreas, públicos e necessidades de comunicação institucional, interna e digital.'"],
  ["desafio: 'Unificar a comunicação institucional de um grupo diversificado, fortalecer a presença digital das marcas, dar visibilidade às iniciativas ESG e criar processos sustentáveis de comunicação — com equipe enxuta e múltiplos públicos simultâneos: colaboradores, lideranças, clientes e comunidade.'", "desafio: 'Atuar de forma transversal entre áreas, lideranças, fornecedores e diferentes públicos, organizando demandas e canais sem perder a consistência da comunicação e o contexto de cada entrega.'"],
  ["estrategia: 'Desenvolvimento de identidade editorial para canais institucionais (Instagram e LinkedIn), estratégia de cobertura de eventos com foco em autoridade e pertencimento, campanha de voluntariado corporativo integrada entre canais internos e externos, e padronização de fluxos, POPs e processos de comunicação.'", "estrategia: 'Minha atuação em redes sociais envolvia planejamento e gestão dos canais, organização de pautas, formatos e calendários, interface com áreas solicitantes, publicação, monitoramento e consolidação de indicadores. Também participei da organização de fluxos, POPs e controles da área.'"],
  ["execucao: 'Toquei a comunicação interna, o e-mail marketing e a presença nas redes sociais. Na Intermodal 2024, coloquei os próprios colaboradores como porta-vozes do estande no LinkedIn e Instagram, gerando recorde de alcance.'", "execucao: 'Atuei em comunicação interna e digital, RD Station, gestão de demandas via Salesforce, redes sociais e acompanhamento de indicadores. Em projetos específicos, como a Intermodal 2024, fiquei responsável pelo planejamento e pela comunicação digital da cobertura.'"],
  ["resultadoTexto: 'Presença digital reestruturada, processos de comunicação padronizados e iniciativas ESG com alcance mensurável e reconhecimento interno.'", "resultadoTexto: 'A experiência consolidou minha atuação em canais, processos, conteúdo e indicadores dentro de uma estrutura corporativa complexa, com entregas realizadas em equipe e responsabilidades específicas por projeto.'"],
  ["subtitulo: 'Comunicação interna, endomarketing e identidade digital — de ponta a ponta.'", "subtitulo: 'Comunicação, marca e produtos em uma empresa de tecnologia para saúde.'"],
  ["contexto: 'A SPDATA é uma empresa de tecnologia para saúde com produtos voltados à gestão de clínicas e hospitais. Sem endomarketing estruturado e sem ações de cultura organizacional, o time não se sentia conectado aos valores e às decisões da empresa. Ao mesmo tempo, a presença digital dos produtos não comunicava os diferenciais técnicos de forma clara.'", "contexto: 'Na SPDATA, empresa que desenvolve soluções ERP para o setor de saúde, atuei em Comunicação e Marketing em um contexto de estruturação da área e de diferentes necessidades de comunicação institucional, interna e de Marketing.'"],
  ["desafio: 'Criar uma comunicação interna que aproximasse as pessoas da liderança, valorizasse o time e colocasse a cultura da empresa em evidência — enquanto padronizava a presença digital das duas linhas de produto com identidade visual diferenciada por público.'", "desafio: 'Organizar entregas de comunicação e marca para públicos internos, liderança, fornecedores, parceiros e diferentes linhas de produtos, preservando consistência visual e clareza.'"],
  ["estrategia: 'Desenvolvimento da campanha SPDATA&Você: identidade visual própria, linha editorial focada em pessoas e benefícios. Redesenho da identidade digital por produto — paleta fria/tech para SPDATA (B2B hospitalar) e paleta quente/humanizada para Minha Clínica (clínicas menores).'", "estrategia: 'Conduzi projetos de comunicação e marca, incluindo a organização e o desenvolvimento visual das linhas de produtos. Também fui responsável por iniciativas de comunicação interna, endomarketing, materiais institucionais e comerciais e apresentações.'"],
  ["execucao: 'Organizei a comunicação interna e o endomarketing. Fiz a campanha institucional que valorizou a equipe, aproximou os colaboradores da diretoria e foi elogiada pelo CEO. Padronizei a cara da empresa nas redes e criei a linguagem visual das linhas de produtos B2B de saúde.'", "execucao: 'Desenvolvi campanhas e conteúdos para diferentes momentos da empresa, trabalhando com Yammer, RD Station, e-mail e materiais gráficos. Também preparava e operava lives pelo Microsoft Teams, do início ao fim, em campanhas e apresentações corporativas.'"],
  ["resultadoTexto: 'Campanha reconhecida pela liderança pelo impacto cultural. Presença digital padronizada e linguagem visual diferenciada por produto — tecnologia médica falando direto com quem precisa entender.'", "resultadoTexto: 'O trabalho reuniu comunicação interna, marca e produtos em uma mesma rotina. Entre os retornos recebidos, a liderança destacou a contribuição da comunicação para tornar a empresa mais viva e ampliar o interesse pelos conteúdos internos.'"],
  ["id: 3, num: '03', empresa: 'Freelance de Marketing, Branding e Conteúdo'", "id: 3, num: '03', empresa: 'move.e'"],
  ["subtitulo: 'Do posicionamento de startups ao relatório de ESG: comunicação que serve pra quem decide.'", "subtitulo: 'Comunicação, Branding, conteúdo e projetos em diferentes formatos.'"],
  ["periodo: '2024–2025'", "periodo: '2025'"],
  ["contexto: 'Startup de tecnologia com solução voltada à gestão e mensuração de indicadores ASG para empresas de médio e grande porte. Com produto em estágio de validação, a empresa não tinha posicionamento institucional definido nem narrativa estruturada para o mercado.'", "contexto: 'Em 2025, passei a desenvolver projetos de comunicação contratados e administrados pela move.e, startup por meio da qual foram conduzidas diferentes iniciativas e entregas.'"],
  ["desafio: 'Construir do zero o posicionamento institucional da marca, criar a arquitetura de mensagens e desenvolver materiais de comunicação para relacionamento com stakeholders, captação de investidores e aproximação com clientes potenciais.'", "desafio: 'Atender projetos com diferentes desafios, formatos e públicos, aplicando repertórios construídos ao longo da minha trajetória em Comunicação e Marketing.'"],
  ["estrategia: 'Diagnóstico de posicionamento e análise de mercado. Definição de arquitetura de mensagens por público (investidores, clientes corporativos, parceiros). Desenvolvimento de narrativa institucional com foco em proposta de valor, diferenciação e credibilidade.'", "estrategia: 'Os projetos envolveram comunicação institucional, Branding, conteúdo, materiais corporativos, apresentações e iniciativas relacionadas a eventos.'"],
  ["execucao: 'Desenvolvi do zero a identidade visual, o guia de marca e as apresentações para colocar a startup de pé no mercado de sustentabilidade e atrair parceiros. Fiz a ponte com investidores e parceiros na Expo Favela 2025 e cuidei dos materiais de relacionamento com cada público.'", "execucao: 'Na Expo Favela 2025, atuei na produção de conteúdo e cobertura digital, com registros e conteúdos produzidos a partir da dinâmica do evento e das necessidades de comunicação do projeto.'"],
  ["resultadoTexto: 'A startup saiu do zero com marca, posicionamento e materiais prontos para conversar com investidores, clientes e parceiros — cada um na sua linguagem.'", "resultadoTexto: 'Os demais projetos serão apresentados à medida que o contexto e os materiais de cada entrega estiverem fechados.'"],
  ["subtitulo: 'Cuidando da comunicação de duas unidades e da mantenedora sem firula, no ritmo da escola.'", "subtitulo: 'Produção multimídia e comunicação em uma rotina de alto volume.'"],
  ["contexto: 'Instituição de ensino tradicional com duas unidades (Funcionários e Anchieta) e uma mantenedora. A comunicação acontecia de forma fragmentada, sem padronização entre canais — cada área puxando para o seu lado e o fluxo de demandas correndo o tempo todo.'", "contexto: 'Na Coordenação de Comunicação, atendia demandas das unidades Funcionários e Anchieta e da instituição, em uma rotina de grande volume, diferentes públicos e forte atuação prática.'"],
  ["desafio: 'Atender duas unidades e a mantenedora ao mesmo tempo, sem perder o ritmo do dia a dia escolar. O desafio era manter a comunicação funcionando — redes, site, campanhas, eventos, impressos — com equipe enxuta e um volume alto de demandas simultâneas vindas de professores, coordenadores e diretores.'", "desafio: 'Dar conta de demandas simultâneas de professores, coordenações, diretorias, áreas administrativas e fornecedores, produzindo materiais para campanhas, eventos e ações institucionais.'"],
  ["estrategia: 'Atuação na linha de frente: atendimento direto às áreas internas, produção de conteúdo multimídia, gestão das redes sociais e do site WordPress, e campanha anual de captação e rematrícula com identidade visual consistente entre os diferentes pontos de contato.'", "estrategia: 'A atuação era essencialmente mão na massa: produção gráfica, fotografia, vídeo, apoio a eventos e atendimento às áreas. Nas redes sociais, o trabalho era operacional, com recebimento e publicação de conteúdos enviados pelas áreas.'"],
  ["execucao: 'Atendi professores, diretores e famílias de frente. Fiz de tudo um pouco: criei campanha de rematrícula, rodei jornal interno, fotografei evento e mantive as redes e o site atualizados, mesmo no ritmo corrido do dia a dia.'", "execucao: 'Produzi peças gráficas, fotografias, vídeos e materiais para campanhas educacionais, religiosas, socioemocionais, eventos e ações de captação. Também realizava atualizações pontuais de conteúdo no site WordPress.'"],
  ["resultadoTexto: 'Comunicação das duas unidades funcionando sem travar, campanhas de rematrícula no ar e as redes e o site sempre atualizados — mesmo com o volume alto de demandas do dia a dia escolar.'", "resultadoTexto: 'Foi onde produção, agilidade e capacidade de atender assuntos muito diferentes passaram a fazer parte da minha rotina.'"],
  ["{ ano: '2025', cargo: 'Freelance de Marketing, Branding e Conteúdo', empresa: 'Autônoma', atual: true }", "{ ano: '2025', cargo: 'Comunicação, Branding e projetos', empresa: 'move.e', atual: true }"],
  ["{ ano: '2018–19', cargo: 'Auxiliar de Comunicação', empresa: 'Colégio Arnaldo' }", "{ ano: '2018–19', cargo: 'Assistente de Comunicação', empresa: 'Colégio Arnaldo' },\n  { ano: '2017', cargo: 'Estagiária · Gerência de Comunicação', empresa: 'Prodemge' },\n  { ano: '2015–17', cargo: 'Estagiária · Comunicação e Apoio', empresa: 'Banco do Brasil' }"],
  ["<em style={{ fontStyle: 'italic', fontWeight: 400, color: T.navy }}>Marketing</em>,{' '}\n              <em style={{ fontStyle: 'italic', fontWeight: 400, color: T.magenta }}>Branding</em>{' '}\n              e Conteúdo.", "Comunicação e Marketing"],
  ["Estratégia, criação e execução integradas — do posicionamento de marca à produção de conteúdo, conectando comunicação, identidade e resultado.", "Atuo entre estratégia e execução, conectando comunicação, conteúdo, marca e canais às necessidades das pessoas e do negócio."],
  ["{ icon: 'marketing' as SiteIconName, label: 'Marketing & Estratégia', cor: T.navy },\n                { icon: 'branding' as SiteIconName, label: 'Branding & Posicionamento', cor: T.magenta },\n                { icon: 'experience' as SiteIconName, label: 'Conteúdo & Narrativa', cor: T.navy },\n                { icon: 'channels' as SiteIconName, label: 'Comunicação Corporativa', cor: T.magenta },", "{ icon: 'branding' as SiteIconName, label: 'Branding', cor: T.navy },\n                { icon: 'experience' as SiteIconName, label: 'Conteúdo multimídia', cor: T.magenta },\n                { icon: 'channels' as SiteIconName, label: 'Canais', cor: T.navy },\n                { icon: 'marketing' as SiteIconName, label: 'Indicadores', cor: T.magenta },"],
]

for (const [from, to] of replacements) s = s.replace(from, to)

// Retira métricas macro sem base completa. Mantém apenas indicadores contextualizados dentro de projetos.
s = s.replace(/\{ valor: '\+7%', label: 'Engajamento orgânico \(2024\)' \},\n\s*\{ valor: '\+33%', label: 'Abertura de comunicados internos' \},\n\s*\{ valor: '\+112%', label: 'Alcance Instagram — Intermodal' \},\n\s*\{ valor: '\+93%', label: 'Alcance LinkedIn — Intermodal' \},\n\s*\{ valor: '\+800', label: 'Pessoas no Dia V' \},\n\s*\{ valor: '8', label: 'Cidades impactadas' \},/, "{ valor: '+112%', label: 'Alcance Instagram · Intermodal 2024' },\n      { valor: '+93%', label: 'Alcance LinkedIn · Intermodal 2024' },")
s = s.replace(/\{ valor: '1', label: 'Campanha de endomarketing completa' \},\n\s*\{ valor: '2', label: 'Identidades visuais por produto' \},\n\s*\{ valor: '100%', label: 'Consistência visual entre canais' \},/, '')
s = s.replace(/\{ valor: '1', label: 'Arquitetura de mensagens estruturada' \},\n\s*\{ valor: '3', label: 'Públicos mapeados' \},/, '')
s = s.replace(/\{ valor: '2', label: 'Campanhas de captação executadas' \},\n\s*\{ valor: '1', label: 'Identidade editorial estruturada' \},/, '')

// Oculta o bloco ainda não autorizado do case move.e sem apagar o código original.
s = s.replace("{/* ── RELATÓRIO ESG ── */}\n      <div style={{ borderTop:`1px solid ${T.rule}`, backgroundColor:'#060f08' }}>", "{/* Bloco reservado para projeto ainda não publicado */}\n      {false && <div style={{ borderTop:`1px solid ${T.rule}`, backgroundColor:'#060f08' }}>")
s = s.replace("      {/* ── NAVEGAÇÃO ── */}\n      <div style={{ padding:'20px 36px', backgroundColor:T.bg", "      }\n\n      {/* ── NAVEGAÇÃO ── */}\n      <div style={{ padding:'20px 36px', backgroundColor:T.bg")

// Corrige nomenclatura pública.
s = s.replaceAll('QualityCert', 'Qualitycert').replaceAll('PolyCare', 'Polycare')

fs.writeFileSync(file, s)
console.log('Revisão editorial aplicada sobre o layout original.')
