import './portfolio.css'
import { Expandable } from './Expandable'
import { timeline } from './portfolioTimeline'
import { sada, spdata, arnaldo, movee } from './portfolioCases'
import profilePhotoColor from './imports/perfil-2-2026-m_dia.jpg'
import heroPhoto from './imports/hero.jpeg'
import contactPhoto from './imports/contato.jpg'
import sadaCover from './imports/rs-sada-0001.jpg'
import intermodalCover from './imports/rs-sada-0002.jpg'
import equipeIntermodal from './imports/equipe-intermodal.png'
import conviteIntermodal from './imports/Convite-inter.jpg'
import entrevista1 from './imports/Entrev-1.png'
import entrevista2 from './imports/Entrev-2.png'
import entrevista3 from './imports/Entrevi-3.png'
import spdataCover from './imports/spdata_voce__5_.png'
import moveeCover from './imports/1-capa.jpg'
import arnaldoCover from './imports/matriculas-17-18__3_.jpg'

function Head({kicker,title,intro}:{kicker:string;title:string;intro?:string}){return <header className="portfolio-section-head"><p className="portfolio-eyebrow">{kicker}</p><h2>{title}</h2>{intro&&<p className="portfolio-section-intro">{intro}</p>}</header>}
function Mosaic({images}:{images:string[]}){return <div className="portfolio-mosaic">{images.map((src,i)=><img key={i} src={src} alt="" loading="lazy" />)}</div>}
const projects=[
 {id:'sada',period:'2022 a 2025',title:'Grupo SADA',subtitle:sada.subtitle,image:sadaCover},
 {id:'spdata',period:'2021 a 2022',title:'SPDATA',subtitle:spdata.subtitle,image:spdataCover},
 {id:'movee',period:'jul a out · 2025',title:'move.e',subtitle:movee.subtitle,image:moveeCover},
 {id:'arnaldo',period:'2018 a 2019',title:'Colégio Arnaldo',subtitle:arnaldo.subtitle,image:arnaldoCover}
]
const sadaTags=['Comunicação corporativa','Comunicação interna','Redes sociais','Conteúdo','Eventos','ESG','RD Station','Salesforce','MLabs','Indicadores']

export default function PortfolioApp(){return <div className="portfolio-shell">
<header className="portfolio-topbar"><div className="portfolio-container portfolio-topbar-inner"><a className="portfolio-brand" href="#top">Sara Madalena</a><nav className="portfolio-nav" aria-label="Navegação principal"><a href="#sobre">Sobre</a><a href="#trajetoria">Experiência</a><a className="portfolio-nav-projects" href="#projetos">Projetos</a><a className="portfolio-nav-contact" href="#contato">Contato</a></nav></div></header>
<main id="top">
<section className="portfolio-hero"><div className="portfolio-hero-copy"><p className="portfolio-eyebrow">Sara Madalena Silva</p><h1>Comunicação<br/>e Marketing</h1><p className="portfolio-degree">Publicitária e especialista em Comunicação e Marketing pela PUC Minas.</p><p className="portfolio-hero-text portfolio-hero-positioning">Atuo entre estratégia e execução, conectando comunicação, conteúdo, marca e canais às necessidades das pessoas e do negócio.</p><div className="portfolio-buttons"><a className="portfolio-button primary" href="#projetos">Ver projetos</a><a className="portfolio-button" href="#contato">Contato</a></div></div><div className="portfolio-hero-image"><img src={heroPhoto} alt="Sara Madalena"/></div></section>
<section id="projetos" className="portfolio-section portfolio-projects-section"><div className="portfolio-container"><Head kicker="Projetos" title="Projetos em diferentes contextos e entregas multidisciplinares, com foco nos públicos e stakeholders."/><div className="portfolio-project-grid">{projects.map((project,index)=><article className={`portfolio-project-card portfolio-project-card-${index+1}`} key={project.id}><a href={`#${project.id}`} className="portfolio-project-link"><div className="portfolio-project-image"><img src={project.image} alt="" loading="lazy"/></div><div className="portfolio-project-copy"><p className="portfolio-project-period">{project.period}</p><h3>{project.title}</h3><p>{project.subtitle}</p><span className="portfolio-project-cta">Ver projeto →</span></div></a></article>)}</div></div></section>
<section id="sobre" className="portfolio-section portfolio-about-section"><div className="portfolio-container"><div className="portfolio-about"><div className="portfolio-about-copy"><Head kicker="Sobre" title="Comunicação que começa entendendo o contexto"/><p>Publicitária e especialista em Comunicação e Marketing pela PUC Minas, construí minha trajetória em diferentes estruturas, segmentos e públicos. Essa diversidade ampliou meu repertório e minha forma de entender a comunicação: quem precisa falar, com quem, por qual canal e para qual necessidade.</p><p>Hoje reúno experiência em comunicação corporativa, conteúdo, marca e canais, combinando criação, organização e leitura de contexto.</p><a className="portfolio-text-link" href="#trajetoria">Ver trajetória →</a><div className="portfolio-edu"><div className="portfolio-info"><h3>Especialista em Comunicação e Marketing</h3><p>MBA · PUC Minas · 2023 a 2024</p></div><div className="portfolio-info"><h3>Publicitária</h3><p>Publicidade e Propaganda · PUC Minas · 2014 a 2017</p></div><div className="portfolio-info"><h3>Marketing Digital Avançado</h3><p>Extensão · ESPM · 2023</p></div><div className="portfolio-info"><h3>Inglês intermediário</h3><p>CCAA · 2010 a 2013<br/>CENEX/FALE UFMG · Em andamento · 2026</p></div></div></div><aside className="portfolio-about-photo"><img src={profilePhotoColor} alt="Sara Madalena" loading="lazy"/></aside></div></div></section>
<section id="trajetoria" className="portfolio-section"><div className="portfolio-container"><Head kicker="Experiência" title="Repertório construído em contextos diferentes" intro="Uma leitura rápida da trajetória profissional, com detalhes disponíveis em cada experiência."/><div className="portfolio-timeline">{timeline.map(item=><article className="portfolio-timeline-row" key={item.empresa}><div className="portfolio-period">{item.periodo}</div><div><h3>{item.empresa}</h3><p className="portfolio-role">{item.cargo}</p><p className="portfolio-summary">{item.resumo}</p><Expandable><ul>{item.detalhes.map(d=><li key={d}>{d}</li>)}</ul></Expandable></div></article>)}</div></div></section>

<section id="sada" className="portfolio-section portfolio-project-detail"><div className="portfolio-container"><div className="portfolio-project-hero"><div className="portfolio-project-hero-copy"><p className="portfolio-eyebrow">Grupo SADA · 2022 a 2025</p><h2>Comunicação e Marketing em uma estrutura corporativa de grande porte</h2><p>Atuação em diferentes frentes e projetos, conectando comunicação corporativa, conteúdo, canais e públicos em uma estrutura multidisciplinar.</p></div><div className="portfolio-project-hero-image"><img src={sadaCover} alt="Projeto Grupo SADA" loading="lazy"/></div></div>
<div className="portfolio-project-context"><div><p className="portfolio-project-label">Contexto</p><p>{sada.contexto}</p></div><div><p className="portfolio-project-label">Minha atuação</p><p>Atuação do planejamento à execução em diferentes iniciativas de comunicação e marketing, com responsabilidades definidas conforme cada projeto e trabalho conjunto com profissionais, áreas e lideranças.</p></div></div>
<article className="portfolio-work-block"><div className="portfolio-work-head"><p className="portfolio-project-label">Projeto em destaque</p><h3>Intermodal South America 2024</h3><p>{sada.intermodal}</p></div><Mosaic images={[intermodalCover,equipeIntermodal,conviteIntermodal,entrevista1,entrevista2,entrevista3]}/><div className="portfolio-metrics">{sada.metricas.map(([v,l])=><div className="portfolio-metric" key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><p className="portfolio-note">{sada.nota}</p></article>
<article className="portfolio-work-block portfolio-work-split"><div><p className="portfolio-project-label">Canais digitais</p><h3>Comunicação digital e redes sociais</h3><p>{sada.redes}</p><p>{sada.equipe}</p></div><aside className="portfolio-evidence"><strong>+7%</strong><p>crescimento orgânico de engajamento nas redes institucionais em 2024.</p><p>Gestão, planejamento, publicação e monitoramento de canais com apoio do MLabs e dos gestores das próprias redes sociais.</p></aside></article>
<article className="portfolio-work-block"><div className="portfolio-work-head"><p className="portfolio-project-label">Comunicação corporativa</p><h3>Comunicação interna, Endomarketing e ESG</h3><p>Atuação em diferentes campanhas, ações e conteúdos corporativos, incluindo temas de saúde e segurança, responsabilidade social, voluntariado, educação corporativa, esporte e comunicação institucional. Dentro dessas frentes, também realizei suporte a lives e transmissões internas, conforme a necessidade das campanhas e ações.</p></div><div className="portfolio-editorial-list"><span>SIPAT</span><span>Programa Na Mão Certa</span><span>Voluntariado</span><span>Escola Corporativa</span><span>SADA Vôlei</span><span>Conteúdo institucional</span></div></article>
<article className="portfolio-work-block portfolio-work-split"><div><p className="portfolio-project-label">Além das entregas</p><h3>Processos, demandas e indicadores</h3><p>{sada.processos}</p><p>{sada.indicadores}</p></div><div><p className="portfolio-project-label">Análise de canais · 2025</p><p>{sada.analise2025}</p></div></article>
<div className="portfolio-project-tags">{sadaTags.map(tag=><span className="portfolio-tag" key={tag}>{tag}</span>)}</div><nav className="portfolio-project-nav" aria-label="Navegação entre projetos"><a href="#projetos">Voltar aos projetos</a><a href="#spdata">SPDATA →</a></nav></div></section>

<section id="spdata" className="portfolio-section portfolio-case-preview portfolio-case-preview-alt"><div className="portfolio-container portfolio-case-preview-grid"><div><p className="portfolio-eyebrow">SPDATA · 2021 a 2022</p><h2>Comunicação, marca e produtos em tecnologia para saúde</h2><p>{spdata.subtitle}</p><a className="portfolio-text-link" href="#spdata">Próximo projeto →</a></div><div className="portfolio-case-preview-image"><img src={spdataCover} alt="Projeto SPDATA" loading="lazy"/></div></div></section>
<section id="movee" className="portfolio-section portfolio-case-preview"><div className="portfolio-container portfolio-case-preview-grid"><div><p className="portfolio-eyebrow">move.e · 2025</p><h2>Comunicação, conteúdo e projetos em diferentes formatos</h2><p>{movee.subtitle}</p></div><div className="portfolio-case-preview-image"><img src={moveeCover} alt="Projeto move.e" loading="lazy"/></div></div></section>
<section id="arnaldo" className="portfolio-section portfolio-case-preview portfolio-case-preview-alt"><div className="portfolio-container portfolio-case-preview-grid"><div><p className="portfolio-eyebrow">Colégio Arnaldo · 2018 a 2019</p><h2>Comunicação para diferentes públicos da comunidade escolar</h2><p>{arnaldo.subtitle}</p></div><div className="portfolio-case-preview-image"><img src={arnaldoCover} alt="Projeto Colégio Arnaldo" loading="lazy"/></div></div></section>
<section id="contato" className="portfolio-section portfolio-contact"><div className="portfolio-container portfolio-contact-grid"><div><p className="portfolio-eyebrow">Contato</p><h2>Tem um projeto? Vamos conversar.</h2><p>Aberta a projetos e oportunidades em Comunicação e Marketing.</p><div className="portfolio-buttons"><a className="portfolio-button" href="https://www.linkedin.com/in/saramadalena/" target="_blank" rel="noreferrer">LinkedIn</a><a className="portfolio-button" href="mailto:comunicacao.saramada@gmail.com">E-mail</a></div></div><div className="portfolio-contact-photo"><img src={contactPhoto} alt="Sara Madalena" loading="lazy"/></div></div></section>
</main><footer className="portfolio-footer"><div className="portfolio-container">Sara Madalena · Comunicação e Marketing</div></footer></div>}
