export const sada = {
 subtitle:'Comunicação integrada, conteúdo e gestão de canais em uma estrutura corporativa de múltiplos públicos, áreas e negócios.',
 contexto:'No Grupo SADA, atuei em Comunicação e Marketing em uma estrutura corporativa ampla, formada por diferentes empresas, segmentos, áreas, públicos e necessidades de comunicação. Minha atuação acontecia de forma transversal e em equipe, conectando planejamento, conteúdo, campanhas, canais internos e externos e acompanhamento de performance.',
 atuacao:'Participava do alinhamento de pautas, planejamento editorial, redação e produção de textos, produção e revisão de conteúdos, publicação, acompanhamento dos canais e consolidação de resultados. A interface envolvia áreas internas, fornecedores, stakeholders e outros profissionais da equipe de Comunicação e Marketing, com responsabilidades distribuídas entre os envolvidos.',
 canais:'Atuei no planejamento, redação, produção e gestão de conteúdo para Instagram, LinkedIn, RD Station e GOintegro. A produção textual fazia parte da rotina, com textos adaptados aos objetivos, públicos, formatos e características de cada canal. Cada canal cumpria um papel diferente dentro da comunicação, e o acompanhamento recorrente de alcance, engajamento, crescimento de comunidade, tráfego, abertura e adesão ajudava a identificar oportunidades e orientar ajustes.',
 instagram:'Entre janeiro e julho de 2024, o Instagram alcançou 1,69 milhão de impressões e 531 mil contas. Em comparação ao período anterior, houve crescimento de 23% no engajamento, 63% nos comentários, 21% nas curtidas, 21% nos cliques no site e 7% nas visitas ao perfil, em um período com 27% menos publicações.',
 linkedin:'Entre janeiro e julho de 2024, a comunidade no LinkedIn passou de 108,8 mil para 128,4 mil seguidores, crescimento de aproximadamente 18%. O canal chegou a registrar alcance mensal de 76,8 mil e engajamento mensal de até 9,14%.',
 rd:'No primeiro semestre de 2024, atuei em comunicações via RD Station para bases com mais de 2,4 mil destinatários. A taxa média de abertura foi de 36,2%, com campanhas chegando a 39,1%.',
 gointegro:'O GOintegro integrava o ecossistema de comunicação interna, com mais de 3 mil usuários cadastrados e até 1,8 mil usuários ativos por mês. A média de usuários ativos no semestre foi de 57,5%, com evolução de 54,3% em fevereiro para 59,6% em junho.',
 campanhas:'Além da gestão contínua dos canais, participei do planejamento e execução de campanhas e projetos ligados a temas institucionais, negócios, sustentabilidade, responsabilidade social, diversidade e marca empregadora. O trabalho envolvia compreender a pauta, o público e os pontos de contato para organizar mensagens e desdobramentos coerentes entre diferentes formatos e canais.',
 design:'Na SADA, minha atuação em design esteve principalmente nos desdobramentos. A partir de identidades, conceitos e direcionamentos já definidos para campanhas e projetos, desenvolvia e adaptava peças para diferentes formatos, canais e necessidades de comunicação, preservando consistência visual e adequação ao contexto de cada entrega. Esse trabalho se conectava à minha atuação em conteúdo e canais, permitindo pensar a aplicação da comunicação também pela lógica do design.',
 interna:'Na comunicação interna, participei de campanhas, conteúdos e iniciativas voltadas à informação e ao relacionamento com os colaboradores. Também atuava no suporte às lives corporativas, contribuindo para sua realização dentro das ações de comunicação interna e para a articulação entre conteúdo, organização e execução.',
 fluxo:'Contexto e demandas → Planejamento → Conteúdo e produção → Canais e campanhas → Públicos → Indicadores e aprendizados',
 processos:'Utilizava Salesforce para triagem, priorização e acompanhamento de demandas, trabalhava com SLAs e participei da criação e melhoria de fluxos e POPs relacionados aos canais e processos da área.',
 intermodal:'Na Intermodal 2024, minha responsabilidade esteve concentrada na comunicação digital do projeto. Fiquei responsável pelo planejamento dessa frente, envolvendo gestão das mídias sociais e canais, calendário de publicações e planejamento da cobertura antes, durante e depois do evento. O planejamento contemplou feed, Stories e Reels, além de pautas e roteiros para vídeos com profissionais da empresa, liderança e cliente.',
 metricas:[['+23%','engajamento no Instagram'],['+18%','crescimento da comunidade no LinkedIn'],['36,2%','abertura média no RD Station'],['+3 mil','usuários cadastrados no GOintegro'],['57,5%','média de usuários ativos no app']],
 metricasIntermodal:[['+112%','alcance no Instagram'],['+93%','alcance no LinkedIn'],['59.246','interações'],['38','Stories'],['1.559','média de interações por Story']],
 nota:'Resultados da cobertura digital da Intermodal 2024. A variação de alcance compara março de 2024 com janeiro de 2024, referência utilizada pela área.',
 analise2025:'A partir do histórico e dos dados dos canais, desenvolvi uma análise e uma proposta de direcionamento para as redes sociais em 2025. O trabalho contemplou análise dos públicos de Instagram e LinkedIn, leitura do desempenho dos canais, análise de concorrentes, SWOT, personas, tom de voz, SMO, objetivos de conteúdo, editorias, sugestões de pautas e indicadores. Os dados foram extraídos dos canais e de ferramentas como MLabs. O planejamento apresentado nesse material não chegou à etapa de implementação.'
}

export const spdata = {
 subtitle:'Comunicação, marca e produtos em uma empresa de tecnologia para saúde.',
 contexto:'Na SPDATA, empresa que desenvolve soluções ERP para o setor de saúde, atuei em Comunicação e Marketing em um contexto de estruturação da área e de diferentes necessidades de comunicação institucional, interna e de Marketing. Minha rotina envolvia relacionamento com público interno, liderança, fornecedores e parceiros, além de demandas relacionadas à marca e aos produtos da empresa.',
 atuacao:'Conduzi projetos de comunicação e marca, incluindo um trabalho de organização e desenvolvimento da identidade das linhas de produtos da SPDATA. Também fui responsável por iniciativas de comunicação interna e endomarketing, produção de conteúdos, materiais institucionais e comerciais, apresentações e outras entregas relacionadas à consistência da comunicação da empresa.',
 marca:'O trabalho com as linhas de produtos envolveu a organização visual de diferentes soluções, preservando sua relação com a marca institucional. Entre os materiais que fazem parte do meu acervo está o trabalho desenvolvido para o SPDATA Minha Clínica, com identidade e aplicações de comunicação para o produto.',
 interna:'Desenvolvi campanhas e conteúdos para diferentes momentos da empresa, incluindo ações de Dia da Mulher, Dia das Mães, Meses Coloridos e outras pautas do calendário interno. O trabalho envolvia Yammer, RD Station, e-mail e materiais gráficos, além da interface com a liderança.',
 lives:'Também preparava e operava lives pelo Microsoft Teams do início ao fim, em campanhas como SPDATA & Você e em apresentações corporativas, incluindo encontros de OKRs.'
}

export const arnaldo = {
 subtitle:'Produção multimídia, campanhas e comunicação de alto volume em duas unidades e na instituição.',
 texto:'Na Coordenação de Comunicação, atendia demandas das unidades Funcionários e Anchieta e da instituição, em uma rotina de grande volume e diferentes públicos. Produzia peças gráficas, fotografias, vídeos e materiais para campanhas educacionais, religiosas, socioemocionais, eventos e ações de captação. Também apoiava a organização de eventos e o atendimento a professores, coordenações, diretorias, áreas administrativas, agência, assessoria de imprensa, gráfica e outros fornecedores.',
 digital:'Nas redes sociais, minha atuação era operacional, com recebimento e publicação de conteúdos enviados pelas áreas nos canais institucionais. Também realizava atualizações pontuais de conteúdo no site WordPress. Foi onde produção, agilidade e capacidade de atender assuntos muito diferentes passaram a fazer parte da minha rotina. As entregas já respondiam também a objetivos de marca, como reputação, alcance, captação, posicionamento e relacionamento.'
}

export const movee = {
 subtitle:'Experiência guarda-chuva para projetos recentes de comunicação, Branding, conteúdo e eventos.',
 expo:'Atuei na produção de conteúdo e cobertura digital durante a Expo Favela 2025, em um projeto contratado e administrado pela move.e. O trabalho envolveu registros e conteúdos produzidos a partir da dinâmica do evento e das necessidades de comunicação do projeto.'
}
