export const sada = {
 subtitle:'Comunicação em uma estrutura corporativa de múltiplos públicos, áreas e canais.',
 contexto:'No Grupo SADA, atuei como Analista de Marketing na Gerência de Comunicação e Marketing, dentro de uma estrutura corporativa ampla, formada por diferentes empresas, segmentos, áreas, públicos e necessidades de comunicação. A Gerência atuava em diferentes frentes, como comunicação interna, institucional, digital, Branding, employer branding, endomarketing e eventos. Meu trabalho acontecia de forma transversal e em equipe, com responsabilidades específicas dentro dessa estrutura.',
 atuacao:'Uma das minhas principais responsabilidades esteve relacionada aos canais corporativos e digitais, especialmente planejamento e gestão de redes sociais, publicação, monitoramento e acompanhamento de indicadores. Também atuava na comunicação interna, e-mail marketing e em diferentes demandas e projetos atendidos pela Gerência.',
 redes:'Fui responsável pelo planejamento e pela gestão das redes sociais, organizando calendário, pautas e publicações a partir dos objetivos dos canais e das diferentes necessidades de comunicação do Grupo. Em 2024, desenvolvi o planejamento de redes sociais contemplando objetivos, persona externa, editorias, calendário anual, pautas, palavras-chave, direcionamentos para interação e acompanhamento dos canais. O planejamento estruturava conteúdos em editorias como Institucional, Negócios, ESG (Environmental, Social and Governance, ou Ambiental, Social e Governança), Campanhas, Gestão de Pessoas, Diversidade, Aniversários e Feiras/Eventos.',
 equipe:'Na rotina, fazia interface com atendimento de Comunicação Corporativa, áreas solicitantes, produção de conteúdo, criação, revisão e outros profissionais envolvidos nas entregas. As responsabilidades eram distribuídas entre diferentes profissionais. Meu trabalho estava concentrado na gestão e no planejamento dos canais e nas atividades relacionadas a essa frente.',
 fluxo:'Planejamento → Pauta → Produção em equipe → Aprovação → Publicação → Monitoramento → Indicadores → Novo planejamento',
 processos:'Utilizava Salesforce para triagem, priorização e acompanhamento de demandas, trabalhava com SLAs e participei da criação e melhoria de fluxos e POPs relacionados aos canais e processos da área. No RD Station, atuava com comunicados internos e campanhas de e-mail marketing dentro das responsabilidades da minha função.',
 indicadores:'Nas redes sociais, acompanhava seguidores, alcance e engajamento em LinkedIn, Instagram e Facebook. Também acompanhava dados relacionados à taxa de abertura no RD Station e à utilização do aplicativo interno. Os indicadores eram reunidos periodicamente e apresentados à gestão.',
 intermodal:'Na Intermodal 2024, minha responsabilidade esteve concentrada na comunicação digital do projeto. Fiquei responsável pelo planejamento dessa frente, envolvendo gestão das mídias sociais e canais, calendário de publicações e planejamento da cobertura antes, durante e depois do evento. O planejamento contemplou feed, Stories e Reels, além de pautas e roteiros para vídeos com profissionais da empresa, liderança e cliente.',
 metricas:[['+112%','alcance no Instagram'],['+93%','alcance no LinkedIn'],['59.246','interações'],['38','Stories'],['1.559','média de interações por Story']],
 nota:'Resultados da cobertura digital da Intermodal 2024. A variação de alcance compara março de 2024 com janeiro de 2024, referência utilizada pela área.',
 analise2025:'A partir do histórico e dos dados dos canais, desenvolvi uma análise e uma proposta de direcionamento para as redes sociais em 2025. O trabalho contemplou análise dos públicos de Instagram e LinkedIn, leitura do desempenho dos canais, análise de concorrentes, SWOT, personas, tom de voz, SMO, objetivos de conteúdo, editorias, sugestões de pautas e indicadores. Os dados foram extraídos dos canais e de ferramentas como MLabs. O planejamento apresentado nesse material não chegou à etapa de implementação.'
}

export const spdata = {
 subtitle:'Comunicação, marca e produtos em uma empresa de tecnologia para saúde.',
 contexto:'Na SPDATA, empresa que desenvolve soluções ERP para o setor de saúde, atuei em Comunicação e Marketing em um contexto de estruturação da área e de diferentes necessidades de comunicação institucional, interna e de Marketing. Minha rotina envolvia relacionamento com público interno, liderança, fornecedores e parceiros, além de demandas relacionadas à marca e aos produtos da empresa.',
 atuacao:'Conduzi projetos de comunicação e marca, incluindo um trabalho de organização e desenvolvimento da identidade das linhas de produtos da SPDATA. Também fui responsável por iniciativas de comunicação interna e endomarketing, produção de conteúdos, materiais institucionais e comerciais, apresentações e outras entregas relacionadas à consistência da comunicação da empresa.',
 marca:'O trabalho com as linhas de produtos envolveu a organização visual de diferentes soluções, preservando sua relação com a marca institucional. Entre os materiais que fazem parte do meu acervo está o trabalho desenvolvido para o SPDATA Minha Clínica, com identidade e aplicações de comunicação para o produto.',
 interna:'Desenvolvi campanhas e conteúdos para diferentes momentos da empresa, incluindo ações de Dia da Mulher, Dia das Mães, Meses Coloridos e outras pautas do calendário interno. O trabalho envolvia Yammer, RD Station, e-mail e materiais gráficos, além da interface com a liderança.',
 lives:'Também preparava e operava lives pelo Microsoft Teams do início ao fim, em campanhas como SPDATA & Você e em apresentações corporativas, incluindo encontros de OKRs.'
}

export const arnaldo = {
 subtitle:'Produção multimídia, campanhas e comunicação de alto volume em duas unidades e na instituição.',
 texto:'Na Coordenação de Comunicação, atendia demandas das unidades Funcionários e Anchieta e da instituição, em uma rotina de grande volume e diferentes públicos. Produzia peças gráficas, fotografias, vídeos e materiais para campanhas educacionais, religiosas, socioemocionais, eventos e ações de captação. Também apoiava a organização de eventos e o atendimento a professores, coordenações, diretorias, áreas administrativas, agência, assessoria de imprensa, gráfica e outros fornecedores.',
 digital:'Nas redes sociais, minha atuação era operacional, com recebimento e publicação de conteúdos enviados pelas áreas nos canais institucionais. Também realizava atualizações pontuais de conteúdo no site WordPress. Foi onde produção, agilidade e capacidade de atender assuntos muito diferentes passaram a fazer parte da minha rotina. As entregas já respondiam também a objetivos de marca, como reputação, alcance, captação, posicionamento e relacionamento.'
}

export const movee = {
 subtitle:'Experiência guarda-chuva para projetos recentes de comunicação, Branding, conteúdo e eventos.',
 expo:'Atuei na produção de conteúdo e cobertura digital durante a Expo Favela 2025, em um projeto contratado e administrado pela move.e. O trabalho envolveu registros e conteúdos produzidos a partir da dinâmica do evento e das necessidades de comunicação do projeto.'
}
