export type TimelineItem = { periodo: string; empresa: string; cargo: string; resumo: string; detalhes: string[] }

export const timeline: TimelineItem[] = [
  { periodo:'2025', empresa:'move.e', cargo:'Comunicação, Branding e Conteúdo', resumo:'Projetos recentes de comunicação contratados e administrados pela move.e, com diferentes desafios, formatos e públicos.', detalhes:['Atuação em comunicação institucional, Branding, conteúdo, materiais corporativos, apresentações e projetos relacionados a eventos e ASG/ESG.','A move.e funciona como experiência guarda-chuva para projetos distintos, preservando o contexto e a responsabilidade específica de cada entrega.'] },
  { periodo:'2022 a 2025', empresa:'Grupo SADA', cargo:'Analista de Marketing', resumo:'Atuação transversal na Gerência de Comunicação e Marketing, com foco em canais corporativos e digitais, redes sociais, comunicação interna, processos e indicadores.', detalhes:['Responsável pelo planejamento e pela gestão de redes sociais, com calendário, pautas, publicação, monitoramento e acompanhamento de indicadores.','Interface com DP, Gente e Gestão, Diversidade e Inclusão, Educação Corporativa, SESMT, Sustentabilidade, Compliance, TI, LGPD, Contábil e Fiscal, Suprimentos, lideranças e outras áreas do negócio.','Uso de Salesforce para triagem e acompanhamento de demandas, trabalho com SLAs e participação na criação e melhoria de fluxos e POPs.'] },
  { periodo:'2021 a 2022', empresa:'SPDATA', cargo:'Analista de Comunicação e Marketing', resumo:'Comunicação, marca e produtos em uma empresa de tecnologia para saúde, com forte autoria em projetos de comunicação interna, endomarketing e identidade.', detalhes:['Condução de projetos de comunicação e marca, incluindo organização e desenvolvimento da identidade das linhas de produtos.','Produção de materiais institucionais e comerciais, apresentações, campanhas internas e materiais gráficos.','Preparação e operação de lives pelo Microsoft Teams do início ao fim, em campanhas como SPDATA & Você e em apresentações corporativas, incluindo encontros de OKRs.'] },
  { periodo:'2020', empresa:'Polycare', cargo:'Analista de Marketing', resumo:'Marketing em interface direta com o Comercial dentro do segmento cirúrgico e de medicina estética.', detalhes:['Desenvolvimento de materiais de comunicação e vendas, identidades para marca, produtos e cursos, conteúdos digitais e portfólio comercial interativo.','Realização de lives pelo Instagram com profissionais e autoridades do setor.','Suporte a eventos e cursos hands-on e relacionamento com clientes, profissionais de saúde, fornecedores e parceiros, incluindo a Sinclair Pharma.'] },
  { periodo:'2019', empresa:'Qualitycert', cargo:'Analista de Marketing', resumo:'Momento em que minha atuação digital começou a ganhar mais estrutura, durante a implementação da frente de Marketing.', detalhes:['Padronização da identidade visual dos canais digitais, calendário editorial, conteúdos, campanhas e experiência inicial com Facebook Ads.','Criação autoral do calendário institucional de 2020, desenvolvido integralmente no Adobe Illustrator.','Participação em ações internas e criação de materiais promocionais e identidades para clientes.'] },
  { periodo:'2018 a 2019', empresa:'Colégio Arnaldo', cargo:'Assistente de Comunicação', resumo:'Uma experiência essencialmente mão na massa, atendendo duas unidades e a instituição em uma rotina de grande volume e diferentes públicos.', detalhes:['Produção de peças gráficas, fotografias, vídeos e materiais para campanhas educacionais, religiosas, socioemocionais, eventos e ações de captação.','Atendimento a professores, coordenações, diretorias, áreas administrativas, agência, assessoria de imprensa, gráfica e fornecedores.','Nas redes sociais, atuação operacional com recebimento e publicação de conteúdos enviados pelas áreas, além de atualizações pontuais no WordPress.','A partir daqui, as entregas passam a responder também a objetivos de marca, como reputação, alcance, captação, posicionamento e relacionamento.'] },
  { periodo:'2017', empresa:'Prodemge', cargo:'Estagiária de Comunicação', resumo:'Comunicação interna durante um período de reestruturação, ainda concentrada nos canais físicos e no ambiente organizacional.', detalhes:['Apoio à assessora de comunicação em atividades relacionadas ao diagnóstico de clima e à comunicação daquele contexto.','Produção gráfica e textual de cartazes e organização dos quadros de avisos.'] },
  { periodo:'2015 a 2017', empresa:'Banco do Brasil', cargo:'Estagiária de Comunicação', resumo:'Minha primeira vivência profissional em comunicação, na área de Comunicação e Apoio da Superintendência de Governo e Varejo.', detalhes:['Apoio a ações internas, eventos, premiações e relacionamento com empregados.','Produção de convites, cartões e materiais gráficos, além de apoio à organização de brindes, documentos e demandas da área.','Contato pontual com assessoria de imprensa e fornecedores gráficos, além de uma proposta de layout para CDs com registros fotográficos de eventos de premiação.'] },
]
