import type { ReactNode } from 'react'
import './portfolio.css'
import { Expandable } from './Expandable'
import { timeline } from './portfolioTimeline'
import { sada, spdata, arnaldo, movee } from './portfolioCases'
import profilePhotoColor from './imports/perfil-2-2026-m_dia.jpg'
import heroPhoto from './imports/hero.jpeg'
import contactPhoto from './imports/contato.jpg'
import sadaCover from './imports/rs-sada-0001.jpg'
import intermodalCover from './imports/rs-sada-0002.jpg'
import equipeIntermodal from './imports/equipe-intermodal.png'
import conviteIntermodal from './imports/Convite-inter.jpg'
import entrevista1 from './imports/Entrev-1.png'
import entrevista2 from './imports/Entrev-2.png'
import entrevista3 from './imports/Entrevi-3.png'
import sadaDesdobramento1 from './imports/Prancheta_1.png'
import sadaDesdobramento2 from './imports/Prancheta_2.png'
import sadaDesdobramento3 from './imports/Prancheta_3.png'
import spdataCover from './imports/spdata_voce__5_.png'
import spdata1 from './imports/spdata_voce__1_.png'
import spdata2 from './imports/spdata_voce__2_.png'
import spdataCI1 from './imports/CI__1_.png'
import spdataCI2 from './imports/CI__2_.png'
import spdataCracha from './imports/campanha-crach___2_.png'
import arnaldoCover from './imports/matriculas-17-18__3_.jpg'
import arnaldo2 from './imports/matriculas-17-18__4_.jpg'
import arnaldo3 from './imports/50-anchieta-18__1_.jpg'
import arnaldo4 from './imports/50-anchieta-18__2_.png'
import arnaldo5 from './imports/ciencias-naturais-19-19__1_.jpg'
import moveeCover from './imports/1-capa.jpg'
import expo1 from './imports/capa-registro-expo.JPG'
import expo2 from './imports/move-expo-a__o.JPG'

const tools=['Adobe Photoshop','Illustrator','InDesign','Premiere Pro','Figma','Canva','RD Station','Salesforce','WordPress','MLabs','Meta Ads & Business','LinkedIn Ads','Google Ads','Microsoft 365','Monday.com','Trello','CorelDRAW']
const ai=['ChatGPT','Claude','Gemini','Adobe Firefly']

function Head({kicker,title,intro}:{kicker:string;title:string;intro?:string}){return <header className="portfolio-section-head"><p className="portfolio-eyebrow">{kicker}</p><h2>{title}</h2>{intro&&<p className="portfolio-section-intro">{intro}</p>}</header>}
function Mosaic({images,label='Evidências visuais do projeto'}:{images:string[];label?:string}){return <div className="portfolio-mosaic" role="group" aria-label={label}>{images.map((src,i)=><img key={i} src={src} alt={`${label}, imagem ${i+1}`} loading="lazy" />)}</div>}
function Case({period,title,subtitle,image,children}:{period:string;title:string;subtitle:string;image:string;children:ReactNode}){return <article className="portfolio-case"><div className="portfolio-case-cover"><div className="portfolio-case-copy"><small>{period}</small><h3>{title}</h3><p>{subtitle}</p></div><div className="portfolio-case-image"><img src={image} alt="" loading="lazy" /></div></div><div className="portfolio-case-details">{children}</div></article>}

export default function PortfolioApp(){return <div className="portfolio-shell">
<header className="portfolio-topbar"><div className="portfolio-container portfolio-topbar-inner"><a className="portfolio-brand" href="#top">Sara Madalena</a><nav className="portfolio-nav"><a href="#sobre">Sobre</a><a href="#trajetoria">Trajetória</a><a href="#cases">Cases</a><a href="#competencias">Competências</a><a href="#reconhecimento">Reconhecimento</a><a href="#contato">Contato</a></nav></div></header>
<main id="top">
<section className="portfolio-hero"><div className="portfolio-hero-copy"><p className="portfolio-eyebrow">Portfólio profissional</p><h1>Comunicação<br/>e Marketing</h1><p className="portfolio-axes">Estratégia · Conteúdo & Narrativas · Comunicação Corporativa · Branding · Canais</p><p className="portfolio-degree">Publicitária e especialista em Comunicação e Marketing pela PUC Minas.</p><p className="portfolio-hero-text">Atuo entre estratégia e execução, conectando comunicação, conteúdo, marca e canais às necessidades das pessoas e do negócio.</p><p className="portfolio-hero-text">Minha trajetória foi construída em diferentes segmentos, estruturas e momentos de comunicação. Isso ampliou meu repertório e minha capacidade de transitar entre áreas, públicos e stakeholders internos e externos, entender contextos distintos e transformar demandas em comunicação aplicável.</p><div className="portfolio-buttons"><a className="portfolio-button primary" href="#cases">Ver cases</a><a className="portfolio-button" href="#contato">Contato</a></div></div><div className="portfolio-hero-image"><img src={heroPhoto} alt="Sara Madalena"/></div></section>
<section id="sobre" className="portfolio-section"><div className="portfolio-container"><div className="portfolio-about"><div className="portfolio-about-copy"><Head kicker="Sobre" title="Comunicação que começa entendendo o contexto"/><p>Minha trajetória em Comunicação e Marketing passou por educação, tecnologia, saúde, certificação digital, logística, mobilidade e indústria, além de experiências ligadas aos setores financeiro e público.</p><p>Trabalhar em estruturas tão diferentes me colocou em contato com muitos assuntos, áreas e públicos. Ao longo desse percurso, aprendi que comunicar também exige entender o contexto: quem precisa falar, com quem, por qual canal, com quais limites e para qual necessidade.</p><p>Comecei em experiências muito ligadas à comunicação interna, ao ambiente presencial e à produção gráfica. Depois vieram a produção multimídia em maior escala, os canais digitais, o Marketing, a interface comercial e o Branding. A partir do Colégio Arnaldo, as entregas passaram a responder também a objetivos de marca, como reputação, alcance, captação, posicionamento e relacionamento. Mais adiante, passei a atuar em estruturas corporativas mais complexas, envolvendo processos, indicadores e diferentes stakeholders.</p><p>Hoje reúno esse repertório em uma atuação que combina criação e organização, conteúdo e canais, leitura de públicos e consistência de marca.</p><div className="portfolio-edu"><div className="portfolio-info"><h3>Especialista em Comunicação e Marketing</h3><p>MBA · PUC Minas · 2023 a 2024</p></div><div className="portfolio-info"><h3>Publicitária</h3><p>Publicidade e Propaganda · PUC Minas · 2014 a 2017</p></div><div className="portfolio-info"><h3>Marketing Digital Avançado</h3><p>Extensão · ESPM · 2023</p></div><div className="portfolio-info"><h3>Inglês intermediário</h3><p>CCAA · 2010 a 2013<br/>CENEX/FALE UFMG · Em andamento · 2026</p></div></div></div><aside className="portfolio-about-photo"><img src={profilePhotoColor} alt="Sara Madalena" loading="lazy"/></aside></div></div></section>
<section id="trajetoria" className="portfolio-section"><div className="portfolio-container"><Head kicker="Trajetória" title="Repertório construído em contextos diferentes" intro="Uma leitura rápida mostra o essencial. Quem quiser aprofundar pode abrir os detalhes de cada experiência."/><div className="portfolio-timeline">{timeline.map(item=><article className="portfolio-timeline-row" key={item.empresa}><div className="portfolio-period">{item.periodo}</div><div><h3>{item.empresa}</h3><p className="portfolio-role">{item.cargo}</p><p className="portfolio-summary">{item.resumo}</p><Expandable><ul>{item.detalhes.map(d=><li key={d}>{d}</li>)}</ul></Expandable></div></article>)}</div></div></section>
<section id="cases" className="portfolio-section"><div className="portfolio-container"><Head kicker="Cases" title="Projetos que mostram a prática" intro="Contexto, responsabilidade e evidência ficam separados para que a página continue leve e cada pessoa escolha o quanto quer aprofundar."/><div className="portfolio-cases">
<Case period="2022 a 2025" title="Grupo SADA" subtitle={sada.subtitle} image={sadaCover}>
<div className="portfolio-case-lead"><div><small>Contexto</small><p>{sada.contexto}</p></div><div><small>Minha atuação</small><p>{sada.atuacao}</p></div></div>
<div className="portfolio-role-head"><small>Como eu atuava</small><span>Um ciclo que conectava planejamento, articulação, execução e leitura de performance.</span></div><div className="portfolio-role-map" aria-label="Ciclo de atuação no Grupo SADA">
<div><small>01</small><strong>Planejamento</strong><span>Leitura de contexto, públicos, pautas, calendário e direcionamento dos canais.</span></div>
<div><small>02</small><strong>Articulação transversal</strong><span>Interface com áreas internas, stakeholders, fornecedores e profissionais envolvidos nas entregas.</span></div>
<div><small>03</small><strong>Execução</strong><span>Redação e produção de textos, conteúdo multimídia, campanhas, publicação, comunicação interna e design de desdobramento.</span></div>
<div><small>04</small><strong>Performance</strong><span>Monitoramento de canais, consolidação de indicadores e leitura de resultados para novos ajustes.</span></div>
</div>
<div className="portfolio-proof-head"><small>Resultados selecionados</small><span>Indicadores dos canais no período analisado</span></div><p className="portfolio-metrics-context">Os números abaixo ajudam a dimensionar os canais e a evolução observada no período. Eles são apresentados como evidências de contexto e acompanhamento, sem atribuir os resultados a uma única ação ou pessoa.</p><div className="portfolio-metrics portfolio-metrics-featured">{sada.metricas.map(([v,l])=><div className="portfolio-metric" key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
<Expandable title="01 · Gestão de canais e performance"><div className="portfolio-scope-tags"><span>Planejamento editorial</span><span>Redação e produção textual</span><span>Conteúdo multimídia</span><span>Publicação</span><span>Gestão de canais</span><span>Relacionamento</span><span>KPIs</span><span>Relatórios</span></div><p>{sada.canais}</p><h4>Instagram | 2024</h4><p>{sada.instagram}</p><h4>LinkedIn | jan–jul/2024</h4><p>{sada.linkedin}</p><h4>RD Station | 1º semestre/2024</h4><p>{sada.rd}</p><h4>GOintegro | 1º semestre/2024</h4><p>{sada.gointegro}</p></Expandable>
<Expandable title="02 · Campanhas, comunicação integrada e design de desdobramento"><div className="portfolio-scope-tags"><span>Institucional</span><span>Negócios</span><span>Sustentabilidade</span><span>Responsabilidade social</span><span>Diversidade</span><span>Marca empregadora</span></div><p>{sada.campanhas}</p><p>{sada.design}</p><div className="portfolio-evidence"><div className="portfolio-evidence-copy"><small>Evidência visual</small><strong>Desdobramento de campanha</strong><span>Aplicações e adaptações visuais dentro de identidade e direcionamento previamente definidos.</span></div><Mosaic label="Desdobramentos visuais de campanha no Grupo SADA" images={[sadaDesdobramento1,sadaDesdobramento2,sadaDesdobramento3]}/></div><div className="portfolio-process-line"><small>Fluxo de trabalho</small><strong>{sada.fluxo}</strong></div><div className="portfolio-process-proof"><div><small>Organização da operação</small><p>{sada.processos}</p></div><div className="portfolio-scope-tags">{sada.processoItens.map(item=><span key={item}>{item}</span>)}</div></div></Expandable>
<Expandable title="03 · Comunicação interna, engajamento e lives"><div className="portfolio-scope-tags"><span>Comunicação interna</span><span>Endomarketing</span><span>GOintegro</span><span>Campanhas</span><span>Produção textual</span><span>Lives corporativas</span><span>Interface com áreas</span></div><p>{sada.interna}</p></Expandable>
<Expandable title="04 · Intermodal 2024 | comunicação digital e cobertura multimídia"><div className="portfolio-project-meta"><span><small>Frente</small>Comunicação digital</span><span><small>Formatos</small>Feed · Stories · Reels · vídeo</span><span><small>Ciclo</small>Antes · durante · depois</span></div><p>{sada.intermodal}</p><div className="portfolio-evidence"><div className="portfolio-evidence-copy"><small>Evidência visual</small><strong>Planejamento + cobertura + conteúdo</strong><span>Registros e peças mostram a articulação entre calendário, canais, formatos e produção multimídia.</span></div><Mosaic label="Cobertura e conteúdo multimídia da Intermodal 2024" images={[intermodalCover,equipeIntermodal,conviteIntermodal,entrevista1,entrevista2,entrevista3]}/></div><div className="portfolio-metrics">{sada.metricasIntermodal.map(([v,l])=><div className="portfolio-metric" key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><p className="portfolio-note">{sada.nota}</p></Expandable>
<Expandable title="05 · Análise e direcionamento de Redes Sociais | 2025"><div className="portfolio-status-note"><strong>Estudo estratégico</strong><span>Proposta desenvolvida a partir do histórico dos canais. Não implementada.</span></div><div className="portfolio-analysis-callout"><small>Ferramenta de apoio</small><strong>MLabs</strong><span>Dados dos canais e da ferramenta foram consolidados para leitura de desempenho e identificação de oportunidades de conteúdo.</span></div><p>{sada.analise2025}</p></Expandable>
<div className="portfolio-case-closure" aria-label="Síntese do case Grupo SADA">
<p className="portfolio-eyebrow">Síntese do case</p>
<h4>Comunicação conectada do planejamento ao acompanhamento.</h4>
<p>Na SADA, meu trabalho combinava leitura de contexto, articulação com diferentes áreas, redação e produção textual, conteúdo multimídia, canais, campanhas, comunicação interna, design de desdobramento e análise de indicadores. A atuação acontecia de forma transversal e em equipe, com responsabilidades próprias dentro de uma estrutura corporativa ampla.</p>
<div className="portfolio-case-signature"><strong>Estratégia + execução</strong><span>Campanhas · articulação transversal · redação e produção textual · conteúdo multimídia · canais · indicadores · design de desdobramento</span></div>
</div>
</Case>
<Case period="2021 a 2022" title="SPDATA" subtitle={spdata.subtitle} image={spdataCover}><Expandable title="Contexto e minha atuação"><p>{spdata.contexto}</p><p>{spdata.atuacao}</p></Expandable><Expandable title="Marca, produtos e comunicação interna"><p>{spdata.marca}</p><p>{spdata.interna}</p><p>{spdata.lives}</p><Mosaic images={[spdata1,spdata2,spdataCI1,spdataCI2,spdataCracha]}/></Expandable></Case>
<Case period="2018 a 2019" title="Colégio Arnaldo" subtitle={arnaldo.subtitle} image={arnaldoCover}><Expandable title="Ver atuação e materiais"><p>{arnaldo.texto}</p><p>{arnaldo.digital}</p><Mosaic images={[arnaldoCover,arnaldo2,arnaldo3,arnaldo4,arnaldo5]}/></Expandable></Case>
<Case period="2025" title="move.e" subtitle={movee.subtitle} image={moveeCover}><Expandable title="Expo Favela 2025"><p>{movee.expo}</p><Mosaic images={[expo1,expo2]}/></Expandable><Expandable title="Outros projetos"><p>Outros projetos serão apresentados à medida que o contexto e os materiais de cada entrega estiverem fechados.</p></Expandable></Case>
</div></div></section>
<section id="competencias" className="portfolio-section"><div className="portfolio-container"><Head kicker="Competências" title="Comunicação e Marketing na prática"/><div className="portfolio-skills"><div className="portfolio-skill"><h3>Branding</h3><p>Identidade e consistência de marca · Posicionamento · Marca institucional · Materiais institucionais e comerciais · Desdobramentos de identidade</p></div><div className="portfolio-skill"><h3>Conteúdo & Narrativas</h3><p>Planejamento editorial · Redação e produção textual · Copywriting · Storytelling · Conteúdo para diferentes públicos e canais · Criação gráfica · Fotografia e vídeo · Campanhas · Cobertura de eventos</p></div><div className="portfolio-skill"><h3>Canais</h3><p>Comunicação corporativa, interna e institucional · Planejamento e gestão de redes sociais · E-mail marketing · Canais internos e digitais · Planejamento editorial · Endomarketing e employer branding</p></div><div className="portfolio-skill"><h3>Indicadores</h3><p>Monitoramento de canais · Alcance e engajamento · Taxas de abertura · Relatórios e controles · Leitura de resultados para apoio ao planejamento</p></div></div><div className="portfolio-tags">{['Gestão de demandas','SLAs','POPs','Fornecedores','Stakeholders','Comunicação de eventos','ESG e sustentabilidade','Governança','Interface com áreas do negócio'].map(x=><span className="portfolio-tag" key={x}>{x}</span>)}</div><Expandable title="Ferramentas"><div className="portfolio-tags">{tools.map(x=><span className="portfolio-tag" key={x}>{x}</span>)}</div><p><strong>IA aplicada ao trabalho</strong></p><div className="portfolio-tags">{ai.map(x=><span className="portfolio-tag" key={x}>{x}</span>)}</div></Expandable></div></section>
<section id="reconhecimento" className="portfolio-section"><div className="portfolio-container"><Head kicker="Reconhecimento profissional" title="O trabalho também é feito de relações" intro="Parte da minha atuação acontece justamente na relação com outras pessoas e áreas. Por isso, a percepção de profissionais que trabalharam comigo também ajuda a contar essa trajetória."/><div className="portfolio-recognition"><article className="portfolio-quote"><p>Reconhecimento pela capacidade de manter o discurso e o alinhamento da área, pela postura mão na massa e pelo companheirismo no trabalho em equipe.</p><strong>Felipe Ramos</strong><span>Coordenação de Comunicação e Marketing · Colégio Arnaldo</span></article><article className="portfolio-quote"><p>Reconhecimento pela contribuição da comunicação para tornar a empresa mais viva e próxima das pessoas e ampliar o interesse pelos conteúdos de comunicação interna.</p><strong>Mário Lonczinski</strong><span>CEO · SPDATA</span></article><article className="portfolio-quote"><p>Reconhecimento pela capacidade de ouvir feedbacks, refletir sobre eles e realizar ajustes com agilidade quando necessário.</p><strong>Leila Vasconcelos</strong><span>Comunicação e Marketing</span></article></div></div></section>
<section id="contato" className="portfolio-section portfolio-contact"><div className="portfolio-container portfolio-contact-grid"><div><p className="portfolio-eyebrow">Contato</p><h2>Vamos conversar?</h2><p>Comunicação muda conforme o contexto. Gosto de entender a demanda, organizar as informações e encontrar a melhor forma de fazer a comunicação funcionar para quem precisa recebê-la.</p><div className="portfolio-buttons"><a className="portfolio-button" href="https://www.linkedin.com/in/saramadalena/" target="_blank" rel="noreferrer">LinkedIn</a><a className="portfolio-button" href="mailto:comunicacao.saramada@gmail.com">E-mail</a></div></div><div className="portfolio-contact-photo"><img src={contactPhoto} alt="Sara Madalena" loading="lazy"/></div></div></section>
</main><footer className="portfolio-footer"><div className="portfolio-container">Sara Madalena · Comunicação e Marketing</div></footer></div>}
